global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-rh'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api_rh:3000']

  - job_name: 'python-processor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python_processor:5000']
